# Generated by Django 2.2.7 on 2020-02-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of registrant', max_length=32, verbose_name='Name')),
                ('gender', models.BooleanField(help_text='True for male, False for female', verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('native_place', models.CharField(help_text='Native Place', max_length=60, verbose_name='Native Place')),
                ('phone_no', models.CharField(help_text='Phone Number', max_length=13, verbose_name='Phone Number')),
                ('blocked', models.BooleanField(default=False, help_text='Block this user or not', verbose_name='Block this user')),
                ('unique_id', models.CharField(max_length=15, verbose_name='Unique profile number')),
                ('pair_unique_id', models.CharField(blank=True, max_length=15, verbose_name='Unique profile number of pair')),
                ('remarks', models.TextField(blank=True, help_text='Other things about user', max_length=161, verbose_name='Remarks')),
            ],
        ),
    ]
