# Generated by Django 2.2.7 on 2020-02-10 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredmembers',
            name='dob',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date of Birth'),
        ),
    ]
