# Generated by Django 2.2.7 on 2020-02-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registeredmembers_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interets', models.CharField(help_text='Interests that we have', max_length=32, verbose_name='Interest')),
                ('category', models.CharField(help_text='category of interests', max_length=32, verbose_name='Category')),
            ],
        ),
    ]
