# Generated by Django 2.2.7 on 2020-02-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredmembers',
            name='interests',
            field=models.TextField(default='', max_length=250),
        ),
    ]
