# Generated by Django 2.2.7 on 2020-02-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registeredmembers_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredmembers',
            name='ktu_reg_no',
            field=models.CharField(default='', max_length=11, verbose_name='KTU Reg No'),
        ),
    ]
