# Generated by Django 2.1.7 on 2020-02-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_registeredmembers_ktu_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredmembers',
            name='remarks',
        ),
    ]
