# Generated by Django 2.1.7 on 2020-02-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_registeredmembers_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredmembers',
            name='remarks',
            field=models.TextField(blank=True, help_text='Other things about user', max_length=161, verbose_name='Remarks'),
        ),
    ]
