# Generated by Django 2.2.7 on 2020-02-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_registeredmembers_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredmembers',
            name='remarks',
            field=models.TextField(blank=True, help_text='Department & Semester', max_length=161, verbose_name='Department & Semester'),
        ),
        migrations.AlterField(
            model_name='registeredmembers',
            name='ktu_reg_no',
            field=models.CharField(default='', max_length=11, verbose_name='Reg No'),
        ),
    ]
